---
# file: site.yml
- name: Configure all servers
  hosts: all
  accelerate: true
  roles:
  - role: common

- name: Configure db servers
  hosts: dbservers
  accelerate: true
  roles:
    - role: dbservers

- name: Configure web servers
  hosts: webservers
  accelerate: true
  roles:
  - role: webservers