---
# file: main.yml

- name: Prepare acceleration on all servers
  sudo: yes
  apt: pkg=python-keyczar state=present update-cache=yes
  tags: setup

- name: set update cache and safe updates
  sudo: yes
  apt: update_cache=yes upgrade=safe
  when: ansible_distribution == 'Ubuntu'

- name: Install Common Packages
  sudo: yes
  apt: >
     pkg={{ item }}
     state=present
     update-cache=yes
  with_items:
     - unattended-upgrades
     - htop
     - vim
  when: ansible_distribution == 'Ubuntu'

- include: users.yml
- include: postfix.yml
- include: logwatch.yml
- include: fail2ban.yml
- include: ufw.yml
- include: auth.yml


