---
# file: main.yml

- name: set update cache
  sudo: yes
  apt: update_cache=yes
  apt: upgrade=safe
  apt: pkg=unattended-upgrades state=present
  when: ansible_distribution == 'Ubuntu'

- name: Install Common Packages
  sudo: yes
  apt: >
     pkg={{ item }}
     state=installed
     update-cache=yes
  with_items:
     - htop
     - vim
  when: ansible_distribution == 'Ubuntu'

- include: users.yml
- include: postfix.yml
- include: logwatch.yml
- include: fail2ban.yml
- include: ufw.yml
- include: auth.yml


